### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by AXCWG** [Bumer-32/I-Want-To-Control-My-Server#7]
A mod crashed on startup!
    net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'iwtcms' at 'ua.pp.lumivoid.iwtcms.PREIWTCMS'!
	    at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	    at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	    at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	    at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
    Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'iwtcms' at 'ua.pp.lumivoid.iwtcms.PREIWTCMS'!
	    at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	    ... 4 more
    Caused by: java.lang.ExceptionInInitializerError
	    at knot//ua.pp.lumivoid.iwtcms.PREIWTCMS.onPreLaunch(PREIWTCMS.kt:15)
	    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	    ... 5 more
    Caused by: java.io.IOException: The system cannot find the path specified
	    at java.base/java.io.WinNTFileSystem.createFileExclusively0(Native Method)
	    at java.base/java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:536)
	    at java.base/java.io.File.createNewFile(File.java:1045)
	    at knot//ua.pp.lumivoid.iwtcms.util.Config.<clinit>(Config.kt:17)
	    ... 7 more

Only for 1.2.0 and 1.1.0, probably config

**Comment by Bumer-32** [comment]
Known issue, for some reason Fabric loader can't find the config folder. This happens only in the built JAR because everything works fine directly in the IDE. Will be fixed in few days
